/**
 * WP0E history endpoints (GET only):
 *   /projects/:id/history              — project history page
 *   /projects/:id/history/export.xlsx  — project history export
 *   /history                           — global history page (exact Owner)
 *   /history/export.xlsx               — global history export (exact Owner)
 * Scope is fixed by the path; the query parser rejects a conflicting scope.
 */
import { auditAction, fail, ok, requirePermission, type Actor } from "./projecthub-actor.server";
import { formatMalaysianDateTime } from "./projecthub-date";
import {
  cellText,
  DEFAULT_COLUMNS,
  HISTORY_COLUMN_BY_KEY,
  HISTORY_EXPORT_CAP,
  parseHistoryQuery,
  sanitiseColumnSelection,
  type HistoryScope,
} from "./projecthub-history";
import { collectHistoryForExport, queryHistory } from "./projecthub-history.server";
import { getProject } from "./projecthub-projects.server";
import { buildXlsx, XLSX_MIME } from "./xlsx-writer.server";

export async function handleHistoryRequest(
  actor: Actor,
  scope: HistoryScope,
  projectId: string | null,
  exportXlsx: boolean,
  search: Record<string, string>,
): Promise<Response> {
  const cid = actor.correlationId;
  if (scope === "global") {
    // Global History is exact N3 `sys-admin` Owner only, resolved server-side.
    if (!actor.session.isOwner) return fail(403, "Global History is available to the Owner", cid);
    const denied = requirePermission(
      actor,
      exportXlsx ? "projecthub:history:export_all" : "projecthub:history:view_all",
    );
    if (denied) return denied;
  } else {
    const denied = requirePermission(
      actor,
      exportXlsx ? "projecthub:history:export_project" : "projecthub:history:view_project",
    );
    if (denied) return denied;
    const visible = await getProject(actor, projectId as string);
    if (!visible.ok) return fail(visible.status, visible.message, cid);
  }

  const params = { ...search };
  if (params["scope"] !== undefined && params["scope"] !== scope) {
    return fail(400, "The history scope does not match this address", cid);
  }
  params["scope"] = scope;
  if (scope === "project") {
    if (params["projectId"] !== undefined && params["projectId"] !== projectId) {
      return fail(400, "The project does not match this address", cid);
    }
    params["projectId"] = projectId as string;
  }
  const parsed = parseHistoryQuery(params);
  if (!parsed.ok) return fail(400, parsed.message, cid);
  const query = parsed.query;

  if (!exportXlsx) {
    const page = await queryHistory(actor, query);
    if (!page.ok) return fail(page.status, page.message, cid);
    const { ok: _ok, ...data } = page;
    return ok(data, cid);
  }

  const exportAction = scope === "global" ? "export_all" : "export_project";
  const collected = await collectHistoryForExport(actor, query, HISTORY_EXPORT_CAP);
  if (!collected.ok) {
    await auditAction(actor, {
      eventType: "projecthub.history.export",
      action: exportAction,
      outcome: collected.tooMany ? "rejected_cap" : "failed",
      targetType: scope,
      targetIdentity: projectId,
      metadata: { filterCount: 0 },
    });
    return fail(collected.status, collected.message, cid);
  }

  const columns = query.columns ?? sanitiseColumnSelection(DEFAULT_COLUMNS[scope], scope);
  const generatedAt = new Date();
  const scopeLabel = scope === "global" ? "Global History" : "Project History";
  let projectLabel = "All visible projects";
  if (scope === "project") {
    const project = await getProject(actor, projectId as string);
    if (project.ok) {
      const p = project.project as { enquiry_reference?: string; title?: string };
      projectLabel = [p.enquiry_reference, p.title].filter(Boolean).join(" — ");
    }
  }
  const rows = collected.rows.map((row) =>
    columns.map((key) =>
      key === "occurredAt" ? formatMalaysianDateTime(row.occurredAt) : cellText(row, key),
    ),
  );
  const workbook = buildXlsx([
    {
      name: scopeLabel,
      header: columns.map((k) => HISTORY_COLUMN_BY_KEY[k].label),
      rows,
      widths: columns.map((k) => (k === "title" ? 48 : k === "occurredAt" ? 18 : 20)),
      table: true,
    },
    {
      name: "Export Info",
      header: ["Field", "Value"],
      widths: [24, 60],
      rows: [
        ["Report", scopeLabel],
        ["Company", actor.session.companyName ?? ""],
        ["Scope", projectLabel],
        ["Generated at (Malaysia time)", formatMalaysianDateTime(generatedAt.toISOString())],
        ["Generated by", actor.session.displayName ?? actor.session.displayEmail ?? ""],
        ["Rows", String(rows.length)],
        [
          "Sort",
          `${HISTORY_COLUMN_BY_KEY[query.sortKey].label} (${query.sortDirection === "asc" ? "ascending" : "descending"})`,
        ],
        ["Filters", collected.applied.length ? collected.applied.join("; ") : "None"],
        ["Date filter basis", "Malaysia time (UTC+08:00), inclusive days"],
        ["Legacy rows", "Rows marked Legacy were recorded before WP0E; labels may be derived."],
        ["Source", "N3 ProjectHub history ledger. Nothing in this file is posted to N3."],
      ],
    },
  ]);

  await auditAction(actor, {
    eventType: "projecthub.history.export",
    action: exportAction,
    outcome: "succeeded",
    targetType: scope,
    targetIdentity: projectId,
    // Only safe counts/labels; never filter values or row content.
    metadata: {
      rowCount: rows.length,
      columnCount: columns.length,
      filterCount: collected.applied.length,
      sortKey: query.sortKey,
      sortDirection: query.sortDirection,
    },
  });

  const stamp = generatedAt.toISOString().slice(0, 10).replace(/-/g, "");
  const filename =
    scope === "global" ? `projecthub-global-history-${stamp}.xlsx` : `project-history-${stamp}.xlsx`;
  return new Response(workbook, {
    status: 200,
    headers: {
      "content-type": XLSX_MIME,
      "content-disposition": `attachment; filename="${filename}"`,
      "cache-control": "no-store",
      "x-content-type-options": "nosniff",
      "x-correlation-id": cid,
    },
  });
}
