import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { readdirSync, statSync } from "node:fs";

const root = process.cwd();

function walk(dir: string): string[] {
  return readdirSync(dir).flatMap((entry) => {
    const full = join(dir, entry);
    return statSync(full).isDirectory() ? walk(full) : [full];
  });
}

const sourceFiles = walk(join(root, "src"));
/**
 * Every browser-reachable source file under src. Server-only modules are
 * excluded by filename, and only the generated Supabase types file is skipped
 * — the integration directory itself IS scanned so a future browser Supabase
 * client added there is detected.
 */
const browserFiles = sourceFiles.filter(
  (f) =>
    /\.(ts|tsx)$/.test(f) &&
    !f.endsWith(".server.ts") &&
    !f.endsWith(".server.tsx") &&
    !f.endsWith(join("integrations", "supabase", "types.ts")),
);

const PROHIBITED_BROWSER_TOKENS = [
  "supabase.auth",
  "VITE_SUPABASE",
  "@supabase/supabase-js",
  "persistSession",
  "autoRefreshToken",
  "attachSupabaseAuth",
  "client.server",
  "SUPABASE_SERVICE_ROLE_KEY",
];

describe("architecture guards", () => {
  it("has no browser Supabase auth files", () => {
    for (const f of [
      "src/integrations/supabase/client.ts",
      "src/integrations/supabase/auth-attacher.ts",
      "src/integrations/supabase/auth-middleware.ts",
      "src/integrations/supabase/previewAuthStorage.ts",
    ]) {
      expect(existsSync(join(root, f)), `${f} must not exist`).toBe(false);
    }
  });

  it("allows exactly two files in the Supabase integration directory", () => {
    const dir = join(root, "src/integrations/supabase");
    expect(readdirSync(dir).sort()).toEqual(["client.server.ts", "types.ts"]);
  });

  it("keeps the generated database types at the approved baseline contract", () => {
    const types = readFileSync(join(root, "src/integrations/supabase/types.ts"), "utf8");
    // The __InternalSupabase.PostgrestVersion field is regenerated by the
    // managed integration; the business contract below is what must not drift.
    expect(types).toMatch(/PostgrestVersion: "\d+\.\d+"/);
    for (const table of [
      "projecthub_tenants",
      "projecthub_user_roles",
      "projecthub_projects",
      "projecthub_project_phases",
      "projecthub_project_team_members",
      "projecthub_boq_versions",
      "projecthub_boq_sections",
      "projecthub_boq_items",
      "projecthub_project_events",
      "projecthub_integration_audit_events",
      "projecthub_n3_request_diagnostics",
      "projecthub_project_sequences",
    ]) {
      expect(types, `${table} must remain in the generated types`).toContain(table);
    }
    expect(types).toContain("projecthub_create_enquiry");
    expect(types).toContain("projecthub_clone_boq_version");
  });

  it("adds no N3 mutation method or path anywhere in the source tree", () => {
    for (const file of sourceFiles.filter((f) => /\.(ts|tsx)$/.test(f))) {
      const src = readFileSync(file, "utf8");
      expect(src, `${file} must not declare a non-GET N3 call`).not.toMatch(
        /n3(Post|Put|Patch|Delete)\s*\(/,
      );
    }
  });

  it("ignores local env files but allows .env.example", () => {
    const ignore = readFileSync(join(root, ".gitignore"), "utf8");
    expect(ignore).toMatch(/^\.env$/m);
    expect(ignore).toMatch(/^\.env\.\*$/m);
    expect(ignore).toMatch(/^!\.env\.example$/m);
  });

  it("keeps .env.example to empty, non-secret, server-only placeholders", () => {
    const example = readFileSync(join(root, ".env.example"), "utf8");
    expect(example).not.toContain("VITE_SUPABASE");
    for (const line of example.split("\n")) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) continue;
      // Every assignment must be an empty placeholder.
      expect(trimmed, line).toMatch(/^[A-Z0-9_]+=$/);
    }
    // No real URL, JWT, key, tenant id or project id may appear.
    expect(example).not.toMatch(/https?:\/\//);
    expect(example).not.toMatch(/eyJ[A-Za-z0-9_-]{5,}/);
    expect(example).not.toMatch(/sb_(publishable|secret)_/);
    expect(example).not.toMatch(/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/i);
  });

  it("has no browser module referencing supabase auth, VITE_SUPABASE or a supabase client", () => {
    for (const file of browserFiles) {
      const src = readFileSync(file, "utf8");
      for (const token of PROHIBITED_BROWSER_TOKENS) {
        expect(src, `${file} must not contain ${token}`).not.toContain(token);
      }
    }
  });

  it("declares an explicit empty functionMiddleware list", () => {
    const start = readFileSync(join(root, "src/start.ts"), "utf8");
    expect(start).toMatch(/functionMiddleware:\s*\[\s*\]/);
    expect(start).not.toContain("attachSupabaseAuth");
  });

  it("keeps the service-role client server-only and fail-closed", () => {
    const client = readFileSync(join(root, "src/integrations/supabase/client.server.ts"), "utf8");
    expect(client).toContain('process.env["SUPABASE_URL"]');
    expect(client).toContain('process.env["SUPABASE_SERVICE_ROLE_KEY"]');
    expect(client).toContain("throw new Error(message)");
    // The key value itself is never logged.
    expect(client).not.toMatch(/console\.[a-z]+\([^)]*SERVICE_ROLE_KEY\s*\)/);
  });
});
