/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CapabilitiesRouteImport } from './routes/capabilities'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as ApiProjecthubSplatRouteImport } from './routes/api/projecthub/$'
import { Route as ApiPublicAuthConnectRouteImport } from './routes/api/public/auth/connect'
import { Route as ApiPublicN3SplatRouteImport } from './routes/api/public/n3/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilitiesRoute = CapabilitiesRouteImport.update({
  id: '/capabilities',
  path: '/capabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjecthubSplatRoute = ApiProjecthubSplatRouteImport.update({
  id: '/api/projecthub/$',
  path: '/api/projecthub/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthConnectRoute = ApiPublicAuthConnectRouteImport.update({
  id: '/api/public/auth/connect',
  path: '/api/public/auth/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicN3SplatRoute = ApiPublicN3SplatRouteImport.update({
  id: '/api/public/n3/$',
  path: '/api/public/n3/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capabilities': typeof CapabilitiesRoute
  '/roles': typeof RolesRoute
  '/settings': typeof SettingsRoute
  '/verification': typeof VerificationRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/projecthub/$': typeof ApiProjecthubSplatRoute
  '/api/public/auth/connect': typeof ApiPublicAuthConnectRoute
  '/api/public/n3/$': typeof ApiPublicN3SplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capabilities': typeof CapabilitiesRoute
  '/roles': typeof RolesRoute
  '/settings': typeof SettingsRoute
  '/verification': typeof VerificationRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/projects': typeof ProjectsIndexRoute
  '/api/projecthub/$': typeof ApiProjecthubSplatRoute
  '/api/public/auth/connect': typeof ApiPublicAuthConnectRoute
  '/api/public/n3/$': typeof ApiPublicN3SplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capabilities': typeof CapabilitiesRoute
  '/roles': typeof RolesRoute
  '/settings': typeof SettingsRoute
  '/verification': typeof VerificationRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/projecthub/$': typeof ApiProjecthubSplatRoute
  '/api/public/auth/connect': typeof ApiPublicAuthConnectRoute
  '/api/public/n3/$': typeof ApiPublicN3SplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/capabilities'
    | '/roles'
    | '/settings'
    | '/verification'
    | '/projects/$projectId'
    | '/projects/new'
    | '/projects/'
    | '/api/projecthub/$'
    | '/api/public/auth/connect'
    | '/api/public/n3/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/capabilities'
    | '/roles'
    | '/settings'
    | '/verification'
    | '/projects/$projectId'
    | '/projects/new'
    | '/projects'
    | '/api/projecthub/$'
    | '/api/public/auth/connect'
    | '/api/public/n3/$'
  id:
    | '__root__'
    | '/'
    | '/capabilities'
    | '/roles'
    | '/settings'
    | '/verification'
    | '/projects/$projectId'
    | '/projects/new'
    | '/projects/'
    | '/api/projecthub/$'
    | '/api/public/auth/connect'
    | '/api/public/n3/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CapabilitiesRoute: typeof CapabilitiesRoute
  RolesRoute: typeof RolesRoute
  SettingsRoute: typeof SettingsRoute
  VerificationRoute: typeof VerificationRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ApiProjecthubSplatRoute: typeof ApiProjecthubSplatRoute
  ApiPublicAuthConnectRoute: typeof ApiPublicAuthConnectRoute
  ApiPublicN3SplatRoute: typeof ApiPublicN3SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capabilities': {
      id: '/capabilities'
      path: '/capabilities'
      fullPath: '/capabilities'
      preLoaderRoute: typeof CapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projecthub/$': {
      id: '/api/projecthub/$'
      path: '/api/projecthub/$'
      fullPath: '/api/projecthub/$'
      preLoaderRoute: typeof ApiProjecthubSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/connect': {
      id: '/api/public/auth/connect'
      path: '/api/public/auth/connect'
      fullPath: '/api/public/auth/connect'
      preLoaderRoute: typeof ApiPublicAuthConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/n3/$': {
      id: '/api/public/n3/$'
      path: '/api/public/n3/$'
      fullPath: '/api/public/n3/$'
      preLoaderRoute: typeof ApiPublicN3SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CapabilitiesRoute: CapabilitiesRoute,
  RolesRoute: RolesRoute,
  SettingsRoute: SettingsRoute,
  VerificationRoute: VerificationRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsNewRoute: ProjectsNewRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ApiProjecthubSplatRoute: ApiProjecthubSplatRoute,
  ApiPublicAuthConnectRoute: ApiPublicAuthConnectRoute,
  ApiPublicN3SplatRoute: ApiPublicN3SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
